// <auto-generated />
using System;
using GSB.Test.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSB.Test.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007172500_AddPoaEvaluationCallback")]
    partial class AddPoaEvaluationCallback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanadCallback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanadCallbacks");
                });

            modelBuilder.Entity("UniqueIdentifierCallback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionId").HasColumnType("nvarchar(max)");
                    b.Property<string>("ActivityId").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("ExternalCode").HasColumnType("nvarchar(max)");
                    b.Property<string>("MapConfirmationTrackingCode").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("OrganId").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("RawJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("RequestId").HasColumnType("nvarchar(max)");
                    b.Property<string>("RuleId").HasColumnType("nvarchar(max)");
                    b.Property<string>("TaskId").HasColumnType("nvarchar(max)");

                    b.HasKey("Id");
                    b.ToTable("UniqueIdentifierCallbacks");
                });

            modelBuilder.Entity("PoaEvaluationCallback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdvocacyEndDate").HasColumnType("nvarchar(max)");
                    b.Property<int>("Code").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("DocType").HasColumnType("nvarchar(max)");
                    b.Property<int>("ErrorCode").HasColumnType("int");
                    b.Property<string>("ErrorMessage").HasColumnType("nvarchar(max)");
                    b.Property<bool>("ExistDoc").HasColumnType("bit");
                    b.Property<bool>("HasPermission").HasColumnType("bit");
                    b.Property<string>("NationalRegisterNo").HasColumnType("nvarchar(max)");
                    b.Property<string>("OrganId").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("OwTrakingCode").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("RawJson").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("Succseed").HasColumnType("bit");

                    b.HasKey("Id");
                    b.ToTable("PoaEvaluationCallbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
